export type Singer = {
  id: number;
  name: string;
  born: string;
  origin: string;
  specialty: string;
  styles: string[];
  experience: string;
  location: string;
  hit: string;
  images: string[];
  bio: [string, string, string];
};

export const singers: Singer[] = [
  {
    id: 0,
    name: "Trabelsi Wajdi",
    born: "Tunisie",
    origin: "Tunisie",
    specialty: "Manager · Troupe Trabelsi & JoyBand",
    styles: ["Management Artistique", "Organisation d'Événements", "Direction Artistique"],
    experience: "+20 ans d'expertise",
    location: "Tunis · International",
    hit: "Manager de Prestige",
    images: ["/chanteur/Trabelsi Wajdi.jpeg"],
    bio: [
      "Wajdi Trabelsi est le manager visionnaire derrière le succès de la Troupe Trabelsi et du JoyBand. Avec une expertise inégalée dans l'industrie musicale tunisienne, he coordonne les plus grands spectacles et gère les carrières des artistes les plus talentueux du pays.",
      "Sa rigueur professionnelle et son sens de l'innovation ont permis à la Troupe Trabelsi de s'imposer comme la référence absolue des mariages de prestige et des événements d'envergure en Tunisie et à l'étranger.",
      "Véritable chef d'orchestre de l'ombre, he veille à l'excellence de chaque prestation, garantissant une qualité artistique et une organisation irréprochable pour offrir au public des moments inoubliables.",
    ],
  },
  {
    id: 1,
    name: "Mohamed Ali Baraket",
    born: "Tunisie",
    origin: "Tunisie",
    specialty: "Registre Populaire & Romantique",
    styles: ["Musique Populaire", "Chanson Romantique", "Influences Orientales"],
    experience: "+15 ans de carrière",
    location: "Tunis · International",
    hit: "Variété Tunisienne",
    images: ["/chanteur/Mahamed ali baraket.jpeg"],
    bio: [
      "Mohamed Ali Baraket est un chanteur tunisien d'exception, particulièrement reconnu pour son talent dans le registre populaire et romantique tunisien. Il s'est imposé sur la scène musicale grâce à sa voix mélodieuse et ses interprétations habitées qui touchent un large public à travers tout le pays.",
      "Son univers artistique est un mélange raffiné de musique populaire tunisienne moderne et d'influences orientales contemporaines. Cette fusion unique lui permet de proposer un répertoire varié, allant des ballades romantiques aux rythmes entraînants, toujours portés par une authenticité profonde.",
      "Figure incontournable des mariages de prestige et des grands événements festifs en Tunisie, Mohamed Ali Baraket captive par son charisme et son professionnalisme. Sa présence sur scène garantit une ambiance à la fois élégante et dynamique, célébrant la richesse de la chanson tunisienne avec passion.",
    ],
  },
  {
    id: 2,
    name: "Hayder Brahim",
    born: "Tunisie",
    origin: "Tunisie",
    specialty: "Nouba & Hadhra Moderne",
    styles: ["Nouba", "Hadhra", "Soufi", "Authentique Tunisien", "Moderne"],
    experience: "+15 ans de carrière",
    location: "Tunisie · Festivals · Événements Culturels",
    hit: "Hadhra & Nouba",
    images: ["/chanteur/Hayder brahim.jpeg"],
    bio: [
      "Hayder Brahim est un chanteur tunisien d'exception, reconnu pour sa voix puissante et sa présence charismatique sur la scène musicale nationale. Véritable ambassadeur de l'identité tunisienne, il se distingue par un style unique qui marie avec élégance la profondeur de la musique authentique aux sonorités de la variété moderne.",
      "Spécialiste de la Nouba tunisienne et de la Hadhra, Hayder Brahim excelle dans l'interprétation des chants spirituels et soufis. Son répertoire, riche et varié, valorise les rythmes traditionnels et le patrimoine andalou classique, tout en intégrant des instruments ancestraux au sein de performances dynamiques et contemporaines.",
      "Organisateur et animateur de spectacles d'envergure, il est une figure incontournable des grands festivals, des soirées culturelles et des mariages prestigieux en Tunisie. Son énergie communicative et son interaction naturelle avec le public créent une ambiance authentique et vibrante, faisant de chaque concert une célébration mémorable de l'âme tunisienne.",
    ],
  },
  {
    id: 3,
    name: "Seif Agerbii",
    born: "Tunisie",
    origin: "Tunisie",
    specialty: "Pop Moderne & Show Dynamique",
    styles: ["Pop Tunisienne Moderne", "Variété Festive", "Influences Orientales"],
    experience: "+10 ans de carrière",
    location: "Tunis · Festivals · International",
    hit: "Spectacle Moderne",
    images: ["/chanteur/Seif Agerbii.jpeg"],
    bio: [
      "Seif Agerbii est une figure montante de la scène musicale tunisienne, reconnu pour son style résolument moderne et ses performances électrisantes. Doté d'une énergie communicative, il s'est imposé comme l'un des artistes les plus dynamiques de sa génération, captivant le public par son charisme naturel.",
      "Spécialisé dans la variété tunisienne moderne et festive, son répertoire fusionne avec succès les rythmes populaires et les influences orientales contemporaines. Sa présence scénique remarquable et son interaction naturelle avec le public transforment chaque apparition en un véritable événement.",
      "Habitué des festivals prestigieux, des mariages haut de gamme et des grandes soirées privées, Seif Agerbii garantit une ambiance vibrante et mémorable. Il incarne parfaitement le renouveau de la fête tunisienne, alliant talent vocal et sens du spectacle pour le plus grand plaisir de ses fans.",
    ],
  },
  {
    id: 4,
    name: "Cheb Sofyen",
    born: "Tunisie",
    origin: "Tunisie",
    specialty: "Variété Moderne & Polyvalente",
    styles: ["Raï Moderne", "Musique Orientale", "Variété Occidentale", "Mezoued", "Festif"],
    experience: "+15 ans de carrière",
    location: "Tunis · Festivals · International",
    hit: "Mix Modern & Populaire",
    images: ["/chanteur/cheb sofyen.jpeg"],
    bio: [
      "Cheb Sofien est un artiste incontournable de la scène tunisienne, reconnu pour son style musical varié et sa capacité unique à fusionner les genres. Apprécié pour son énergie débordante sur scène, il s'est imposé comme une figure majeure des mariages de prestige, des festivals et des grands spectacles à travers tout le pays.",
      "Son univers musical est d'une richesse exceptionnelle, mêlant avec brio le Raï moderne, la musique orientale et les variétés occidentales en français et en anglais. Cette polyvalence lui permet d'intégrer également le Mezoued traditionnel à des compositions festives et modernes, créant un son qui lui est propre et immédiatement reconnaissable.",
      "Véritable showman doté d'une identité artistique affirmée, Cheb Sofien sait adapter ses performances à tous les publics et à toutes les ambiances. Ses spectacles sont un voyage sonore où les rythmes tunisiens rencontrent les sonorités internationales, garantissant une atmosphère dynamique, moderne et résolument festive pour chaque célébration.",
    ],
  },
  {
    id: 5,
    name: "Sifon",
    born: "Tunisie",
    origin: "Tunisie",
    specialty: "Style Moderne & Énergie Scénique",
    styles: ["Moderne", "Festif", "Fusion Orientale-Occidentale", "Guitare Live"],
    experience: "+10 ans de carrière",
    location: "Tunisie · Festivals · Événements de prestige",
    hit: "Identité Artistique Originale",
    images: ["/chanteur/Sifon.jpeg"],
    bio: [
      "Sifon est un artiste tunisien connu pour son style moderne et son énergie débordante sur scène. Figure montante et incontournable de la scène musicale actuelle en Tunisie, il se distingue par des performances festives qui captivent instantanément son public grâce à une présence vibrante et une identité artistique originale.",
      "Son univers musical est un mélange harmonieux de rythmes modernes, mêlant habilement ambiances orientales et occidentales sous des influences contemporaines. Sa particularité artistique réside dans sa capacité à jouer de la guitare durant ses performances, ajoutant une touche instrumentale unique et une authenticité musicale à ses prestations live.",
      "Très apprécié lors de soirées privées, de festivals et de mariages de prestige, Sifon crée une ambiance dynamique et festive adaptée à tous les publics. Sa maîtrise de la scène et son interaction avec l'audience font de lui un artiste de choix pour des événements modernes, élégants et résolument tournés vers l'excellence artistique.",
    ],
  },
  {
    id: 6,
    name: "Zied Gharsa",
    born: "Tunis, 1975",
    origin: "Tunis, Tunisie",
    specialty: "Maître du Malouf · Cheikh Al Malouf",
    styles: ["Malouf", "Mouachahs", "Chant Soufi", "Classique Tunisien"],
    experience: "+35 ans de carrière",
    location: "Tunis · La Rachidia · International",
    hit: "Alech Thayyar Fiyya",
    images: ["/chanteur/Zied gharsa.jpeg"],
    bio: [
      "Zied Gharsa, né le 17 mars 1975 à Tunis, est un musicien, chanteur et compositeur d'exception, surnommé « Cheikh Al Malouf ». Fils du regretté Taher Gharsa, il perpétue une tradition familiale prestigieuse, ayant été formé dès son plus jeune âge par son père, lui-même élève du grand Khemaïs Tarnane.",
      "Virtuose multi-instrumentiste (oud, violon, piano), il dirige depuis 2006 l'orchestre et la chorale de La Rachidia, institution gardienne de la musique tunisienne. En 2025, il a franchi une nouvelle étape en fondant sa propre Académie, dédiée à la transmission du malouf et des arts traditionnels aux jeunes générations.",
      "Distingué Officier de l'Ordre national du Mérite, il captive le public par sa voix de ténor unique et ses interprétations magistrales de classiques comme « Alech Thayyar Fiyya » ou « Chouchana ». Sa performance récente à l'Opéra de Tunis en 2026 confirme son statut de figure emblématique et incontournable de l'âme musicale tunisienne.",
    ],
  },
  {
    id: 7,
    name: "Nabiha Karaouli",
    born: "Gafsa, Tunisie",
    origin: "Gafsa, Tunisie",
    specialty: "Légende de la Chanson Tunisienne",
    styles: ["Patrimoine Tunisien", "Poésie Moderne", "Électro-Percussif", "Traditionnel"],
    experience: "+35 ans de carrière",
    location: "Tunis · Gafsa · International",
    hit: "Metchaouka",
    images: ["/chanteur/Nabiha Karaouli.jpeg"],
    bio: [
      "Nabiha Karaouli, originaire de Gafsa, est une figure magistrale et emblématique de la scène musicale tunisienne. Révélée en 1987 par Anouar Braham dans le spectacle culte « Passion de fleur », elle possède l'une des voix les plus reconnaissables du Maghreb : rauque, puissante, et dotée d'un vibrato d'une intensité rare qui sublime chaque note.",
      "Véritable intellectuelle de la musique, diplômée en littérature et en musicologie, elle excelle dans l'art de marier le patrimoine ancestral à la poésie moderne et aux sonorités électro-percussives contemporaines. Ses succès éternels comme « Metchaouka » et « Ken Kalbi Mtaouaani » font d'elle la gardienne d'un héritage qu'elle réinvente sans cesse avec noblesse.",
      "Femme d'engagements, elle a clôturé en mars 2026 le prestigieux Festival de la Médina de Tunis, prouvant que son magnétisme scénique reste intact après quatre décennies de carrière. Sa présence apporte une aura de prestige et une profondeur culturelle exceptionnelle, faisant de chaque événement une cérémonie hors du temps, ancrée dans la plus pure tradition de l'élégance tunisienne.",
    ],
  },
  {
    id: 8,
    name: "Lotfi Bouchnak",
    born: "Tunis, 1954",
    origin: "Tunis, Tunisie",
    specialty: "Malouf & Tarab Classique",
    styles: ["Malouf", "Tarab", "Soufi", "Arabo-Andalou"],
    experience: "+45 ans de carrière",
    location: "Tunis · Le Caire · International",
    hit: "Le Pavarotti Tunisien",
    images: ["/chanteur/Lotfi Bouchnak.jpeg"],
    bio: [
      "Lotfi Bouchnak, né le 18 janvier 1954 à Tunis, est une légende vivante de la musique arabe, surnommé le « Pavarotti tunisien ». Maître incontesté du Malouf et du Tarab, sa voix de ténor d'une puissance phénoménale résonne depuis des décennies dans les plus prestigieuses salles du monde, de l'Opéra du Caire à l'Olympia de Paris.",
      "Artiste engagé et humaniste, il a été nommé Ambassadeur pour la Paix par l'ONU en 2004, mettant son talent au service des causes universelles. Son répertoire, riche et varié, embrasse aussi bien les classiques d'Oum Kalthoum que des compositions soufies et des créations originales qui touchent toutes les générations.",
      "En 2025, il continue de marquer l'histoire avec des performances magistrales, notamment son concert mémorable à l'amphithéâtre de Hammamet en juillet. Sa présence sur scène est une expérience mystique où l'excellence technique rencontre une émotion pure, faisant de lui le gardien suprême de l'âme musicale tunisienne.",
    ],
  },
  {
    id: 9,
    name: "Raouf Maher",
    born: "Médenine, Tunisie",
    origin: "Sud Tunisien",
    specialty: "Patrimoine du Sud & Fusion Pop",
    styles: ["Traditionnel du Sud", "Mezoued", "Pop", "Techno-Folk"],
    experience: "+15 ans de carrière",
    location: "Médenine · Tunis · Carthage",
    hit: "Sandida",
    images: ["/chanteur/Raouf Maher.jpeg"],
    bio: [
      "Raouf Maher, originaire de Médenine, est l'un des ambassadeurs les plus passionnés du Sud tunisien. Double lauréat du premier prix au Festival de la chanson tunisienne en 2006 et 2007, il a su conquérir tout le pays en mettant en musique les récits, l'histoire et la noblesse des coutumes de sa région natale.",
      "Sa musique est une fusion audacieuse où le Mezoued et le Tabbal rencontrent des sonorités pop et techno contemporaines. Son tube signature « Sandida », un hommage vibrant à la femme tunisienne, est devenu un hymne national. Sa popularité immense sur YouTube (classé 8e en Tunisie) témoigne de l'amour profond du public pour son authenticité.",
      "Artiste de scène accompli, capable de remplir le Théâtre de Carthage à guichets fermés, Raouf Maher apporte une intensité et une fierté rares à chaque performance. Son actualité reste bouillonnante avec ses derniers titres « Naghar » (2024) et « Ya Chog » (2026), faisant de lui une figure incontournable des célébrations qui honorent l'âme de la Tunisie.",
    ],
  },
  {
    id: 10,
    name: "Chams Eddine Bacha",
    born: "Tunisie",
    origin: "Tunis, Tunisie",
    specialty: "Showman · Variété Pop",
    styles: ["Variété Tunisienne", "Pop Arabe", "Spectacle Live"],
    experience: "+20 ans de scène",
    location: "Tunis · Dubaï · Paris",
    hit: "Le Roi du Spectacle",
    images: ["/chanteur/Shemss edin Bacha.jpeg"],
    bio: [
      "Chams Eddine Bacha est l'un des artistes les plus polyvalents et médiatisés de la scène tunisienne. Véritable showman, il allie une voix puissante à un sens inné du spectacle, ce qui en fait l'un des invités les plus convoités pour les mariages de prestige et les événements haut de gamme.",
      "Au-delà de sa carrière musicale, il est une figure incontournable du paysage médiatique tunisien, intervenant régulièrement comme chroniqueur et présentateur sur des chaînes majeures comme Attessia TV et sur les ondes de Mosaïque FM. Sa personnalité affirmée et son franc-parler font de lui un artiste qui ne laisse personne indifférent.",
      "Reconnu pour ses performances scéniques électrisantes et ses mises en scène soignées, Chams Eddine Bacha incarne le glamour et l'énergie de la fête tunisienne moderne. Sa présence garantit une ambiance exceptionnelle, transformant chaque célébration en un moment unique et mémorable.",
    ],
  },
  {
    id: 11,
    name: "Nour Chiba",
    born: "Tunisie, 1980",
    origin: "Tunis, Tunisie",
    specialty: "Mezoued Moderne · Pop Arabe",
    styles: ["Mezoued", "Pop Arabe", "Patrimoine Tunisien", "Folk"],
    experience: "+20 ans de carrière",
    location: "Tunis · Sahel · Sud Tunisien",
    hit: "Bouset Khala",
    images: ["/chanteur/Nour Chiba.jpeg"],
    bio: [
      "Nour Chiba, né le 26 juillet 1980, est une figure centrale de la musique populaire tunisienne moderne. Acteur et chanteur charismatique, il a su réinventer le Mezoued en lui insufflant une énergie pop contemporaine, tout en restant profondément ancré dans les traditions musicales du Sud et du Sahel tunisien.",
      "Depuis ses débuts en 2003 avec « Ya Mezri Hell El Biben », il a enchaîné les succès populaires comme « Bouset Khala » et « Netsahwek ». Son talent de compositeur s'est illustré à travers de nombreux albums comme Khomsa ou Nerja3lek (2021), et plus récemment avec son single « Mariouma » sorti en mai 2025.",
      "Véritable icône de la jeunesse et des fêtes populaires, Nour Chiba est réputé pour sa générosité sur scène et sa capacité à faire danser les foules au son du patrimoine revisité. Malgré les épreuves récentes qui ont marqué son parcours en 2026, son héritage musical reste l'un des plus aimés et écoutés de Tunisie.",
    ],
  },
  {
    id: 12,
    name: "Sirine Miled",
    born: "Sfax, Tunisie",
    origin: "Sfax, Tunisie",
    specialty: "Contemporary Pop · Hip-Hop",
    styles: ["Pop Arabe", "Hip-Hop", "Dance", "Techno"],
    experience: "+5 ans de carrière",
    location: "Tunis · Sfax · Dubaï",
    hit: "Yallah",
    images: ["/chanteur/Sirine Miled.jpeg"],
    bio: [
      "Sirine Miled, originaire de Sfax, est l'une des figures de proue de la nouvelle scène pop contemporaine en Tunisie. Avec un style audacieux qui mêle habilement les racines arabes aux sonorités occidentales comme la dance et la techno, elle s'est imposée grâce à des clips visuellement percutants et une énergie moderne.",
      "Révélée au début des années 2020, elle a conquis le public avec son album « Mi-Ange Mi-Demon » et des tubes tels que « Yallah » (plus d'un million de vues) et « PAM PAM ». Ses collaborations, notamment avec Si Lemhaf sur « All Night », témoignent de sa versatilité et de son influence croissante sur la jeunesse tunisienne.",
      "Artiste connectée et charismatique, Sirine Miled incarne le renouveau de la musique tunisienne. Sa présence apporte une touche de fraîcheur et de dynamisme aux événements les plus branchés, faisant d'elle une artiste incontournable pour des cérémonies qui souhaitent allier tradition et tendances mondiales.",
    ],
  },
  {
    id: 13,
    name: "Sherine Lajmi",
    born: "Tunis, 1995",
    origin: "Tunis, Tunisie",
    specialty: "Variété Populaire & Orientale",
    styles: ["Variété Tunisienne", "Variété Orientale", "Pop Arabe", "Dialecte Marocain"],
    experience: "+15 ans de carrière",
    location: "Tunis · International",
    hit: "Ya Donia Yezzina",
    images: ["/chanteur/Sherine lajmi.jpeg"],
    bio: [
      "Sherine Lajmi, née le 11 décembre 1995 à Tunis, est l'une des artistes les plus polyvalentes et audacieuses de la nouvelle scène tunisienne. Révélée au grand public dès 2011, elle a marqué les esprits avec sa voix puissante sur le générique culte de la série « Awled Moufida », en collaboration avec le rappeur Balti.",
      "Artiste libre et productrice indépendante, elle refuse de s'enfermer dans un registre unique, explorant avec succès la variété tunisienne, orientale et même le dialecte marocain avec son clip « Ki Leum Ki Ghada » tourné à Chefchaouen en 2024. Ses succès comme « Sabra » et « Ya Mima » témoignent de sa capacité à toucher un public intergénérationnel.",
      "En 2025, elle continue de dominer les charts avec ses titres « Ta3Abni Fra9Ou » et « Chah Chah », tout en réalisant ses rêves les plus chers, comme sa performance mémorable sur la scène du Théâtre municipal de Tunis. Sherine Lajmi apporte une touche de fraîcheur, de modernité et une énergie débordante aux événements les plus prestigieux.",
    ],
  },
  {
    id: 14,
    name: "Zahra Fares",
    born: "Tunisie",
    origin: "Tunis, Tunisie",
    specialty: "Mainstream Pop · Variété Arabe",
    styles: ["Pop Arabe", "Pop Contemporaine", "Ballade Émotionnelle"],
    experience: "+5 ans de carrière",
    location: "Tunis · Dubaï · Réseaux Sociaux",
    hit: "Ken Kteb",
    images: ["/chanteur/Zahra Fares.jpeg"],
    bio: [
      "Zahra Fares est l'une des nouvelles étoiles montantes de la pop tunisienne. Avec une voix captivante et un style résolument moderne, elle a su conquérir une audience fidèle en fusionnant les mélodies traditionnelles avec les tendances pop mainstream mondiales.",
      "Son ascension fulgurante est marquée par des succès digitaux impressionnants, notamment son titre « Ken Kteb » qui a dépassé le million de vues, et son dernier single « Yalla Jahzin » sorti en 2024. Son album « Mosrar » (2022) a également révélé toute l'étendue de sa puissance vocale à travers des ballades émotionnelles poignantes.",
      "Classée parmi les artistes les plus influents de la scène tunisienne actuelle avec près d'un demi-million d'abonnés sur Instagram, Zahra Fares apporte une énergie fraîche et communicative à chaque performance. Elle représente parfaitement cette nouvelle génération d'artistes talentueux qui redéfinissent les standards de la fête tunisienne moderne.",
    ],
  },
  {
    id: 15,
    name: "Mehdi Ayachi",
    born: "Kairouan, Tunisie",
    origin: "Kairouan, Tunisie",
    specialty: "Chant Soufi & Tarab Moderne",
    styles: ["Soufi", "Malouf", "Tarab", "Fusion Électro-Bédouine"],
    experience: "+15 ans de carrière",
    location: "Tunis · Kairouan · Munich · International",
    hit: "Ziara (Lead Singer)",
    images: ["/chanteur/Mehdi Ayachi.jpeg"],
    bio: [
      "Mehdi Ayachi, originaire de la ville sainte de Kairouan, est une figure de proue du chant soufi et du Tarab en Tunisie. Premier Tunisien à remporter « The Voice Ahla Sawt » en 2019, he est devenu une véritable fierté nationale, captivant des millions de spectateurs par sa voix habitée et sa maîtrise exceptionnelle du patrimoine vocal arabe.",
      "Ancien chanteur principal du spectacle culte « Ziara » de Sami Lajmi, il a su faire évoluer son art vers des projets personnels audacieux comme « Trig », qui fusionne les couleurs soufies et bédouines avec des sonorités électroniques. Producteur indépendant depuis 2024, il défend une vision artistique authentique et profondément ancrée dans ses racines.",
      "De Kairouan aux scènes internationales comme Munich en 2025, Mehdi Ayachi transporte son public dans un voyage spirituel et mélodique d'une rare intensité. Sa présence apporte une dimension mystique et un prestige incomparable aux événements d'exception, célébrant l'excellence de la musique tunisienne sous toutes ses formes.",
    ],
  },
  {
    id: 16,
    name: "Fawzi Ben Gamra",
    born: "Tunisie, 1959",
    origin: "Tunis, Tunisie",
    specialty: "Chant Spirituel & Mezoued",
    styles: ["Soufi", "Mezoued", "Méditation", "Spirituel"],
    experience: "+30 ans de carrière",
    location: "Tunis · Festivals Soufis · International",
    hit: "Allah Ya Allah",
    images: ["/chanteur/Fawzi Ben Gamra.jpeg"],
    bio: [
      "Fawzi Ben Gamra, né en 1959, est un artiste dont le parcours a profondément marqué la culture tunisienne. Après des débuts fulgurants dans le Mezoued populaire dès 1992, où il est devenu une figure incontournable des mariages tunisiens, il a opéré en 2001 un tournant spirituel majeur qui a redéfini sa carrière.",
      "Aujourd'hui maître du chant soufi et des louanges divines, il offre des performances empreintes de sérénité et de dévotion. Ses titres emblématiques comme « Allah Ya Allah » ou ses classiques populaires tels que « Bent Hlal » témoignent d'une versatilité rare qui lui permet de toucher un public très large, allant du festif au méditatif.",
      "Personnalité médiatique respectée, il intervient également comme chroniqueur sur des chaînes prestigieuses. Son dernier single « Thasib Fia Aali Fat », sorti en janvier 2026, confirme sa place d'artiste intemporel capable de sublimer chaque cérémonie par une dimension spirituelle profonde et authentique.",
    ],
  },
  {
    id: 18,
    name: "Houcine Ameur El Efrit",
    born: "Tunisie",
    origin: "Tunisie",
    specialty: "Folk Arabe · Maître du Oud",
    styles: ["Folk Arabe", "Moyen-Oriental", "Classique Tunisien", "Virtuose Oud"],
    experience: "+30 ans de carrière",
    location: "Tunis · L'Ariana · International",
    hit: "Maître du Oud",
    images: ["/chanteur/Houcine Ameur El Efrit.jpeg"],
    bio: [
      "Houcine Ameur El Efrit est un chanteur et musicien tunisien d'exception, reconnu comme un maître incontesté du folk arabe et de la musique moyen-orientale. Véritable virtuose du oud, il sculpte des mélodies d'une délicatesse rare qui résonnent avec une authenticité profonde, captivant les mélomanes les plus exigeants.",
      "Son univers sonore est un voyage sensoriel qui transporte l'auditeur des ruelles animées de Tunis aux oasis sereines du Sahara. Fidèle aux racines du patrimoine tunisien, il fusionne habilement les composantes traditionnelles avec des influences contemporaines, créant un son dynamique et chargé d'émotion humaine.",
      "Artiste de scène accompli, remarqué lors d'événements prestigieux comme les Layeli Tunivisions, il se consacre à la préservation de la pureté du folk arabe face à la mondialisation. Sa présence apporte une noblesse culturelle et une profondeur musicale inégalée, transformant chaque célébration en un moment de connexion authentique.",
    ],
  },
  {
    id: 19,
    name: "Amina Faker",
    born: "Tunisie",
    origin: "Tunis, Tunisie",
    specialty: "Pop Tunisienne & Orientale",
    styles: ["Pop Arabe", "Variété", "Moderne", "Ballade"],
    experience: "+15 ans de carrière",
    location: "Tunis · Hammamet · International",
    hit: "Mestanniye",
    images: ["/chanteur/Amina Fakhet.jpeg"],
    bio: [
      "Amina Faker est une chanteuse talentueuse reconnue pour sa voix cristalline et son style moderne. Depuis ses débuts, elle a su s'imposer sur la scène tunisienne et arabe grâce à des titres accrocheurs et une présence scénique pleine de fraîcheur et d'élégance.",
      "Son répertoire allie avec succès les sonorités pop contemporaines et les influences orientales, ce qui lui permet de toucher un public varié et intergénérationnel. Ses succès comme « Mestanniye » témoignent de sa capacité à interpréter des chansons qui restent gravées dans la mémoire des mélomanes.",
      "Artiste dynamique et souriante, Amina Faker est une habituée des soirées prestigieuses et des festivals d'été. Son énergie positive et son talent vocal font d'elle une artiste très sollicitée pour apporter une touche de glamour et de joie aux célébrations les plus mémorables.",
    ],
  },
  {
    id: 20,
    name: "Manel Amara",
    born: "Tunisie, 1981",
    origin: "Tunis, Tunisie",
    specialty: "Pop Star · Actrice · Influenceuse",
    styles: ["Pop Arabe", "Variété Française", "Pop Internationale", "Show"],
    experience: "+20 ans de carrière",
    location: "Tunis · Dubaï · Réseaux Sociaux",
    hit: "Njib El Money",
    images: ["/chanteur/Manel Amara.jpeg"],
    bio: [
      "Manel Amara, née le 7 février 1981, est l'une des personnalités les plus dynamiques et polyvalentes du paysage artistique tunisien. Star de la pop, actrice de talent (notamment dans la série culte « Pour les beaux yeux de Catherine ») et influenceuse majeure, elle incarne une modernité assumée et un sens aigu du spectacle.",
      "Sa carrière musicale se distingue par une capacité unique à réinventer les classiques français comme « La Vie en rose » tout en dominant les charts avec des tubes pop tels que « Njib El Money » ou « Ellila Eersi ». Avec plus de 500 000 abonnés sur YouTube, elle est une véritable icône de la culture pop tunisienne contemporaine.",
      "Personnalité audacieuse et avant-gardiste, Manel Amara transforme chaque apparition en un événement médiatique. Son énergie débordante, son charisme scénique et son expertise des réseaux sociaux en font une artiste incontournable pour des événements vibrants, glamour et résolument tournés vers l'avenir.",
    ],
  },
  {
    id: 21,
    name: "Mariem Noureddine",
    born: "Tunisie",
    origin: "Tunisie",
    specialty: "Musique Soufie & Mezoued",
    styles: ["Mezoued", "Soufi", "Folklorique Arabe", "Show Mystique"],
    experience: "+15 ans de carrière",
    location: "Tunis · Oudhna · International",
    hit: "Yamanou",
    images: ["/chanteur/Mariem Noureddine.jpeg"],
    bio: [
      "Mariem Noureddine, née en Tunisie, est une artiste d'exception qui porte avec fierté l'héritage de son père, le célèbre Noureddine Kahlaoui. Pionnière audacieuse, elle est la première femme à s'être imposée dans l'univers historiquement masculin du Mezoued, fusionnant avec brio les rythmes de la cornemuse tunisienne et la profondeur du chant soufi.",
      "Créatrice du spectacle phénoménal « Rebaykha », elle offre une expérience scénique totale mêlant dhikr, rituels ancestraux et mise en scène moderne. Ses succès comme « Yamanou », « Olala » et « Jaoui » témoignent de sa capacité unique à revitaliser le patrimoine folklorique pour les nouvelles générations.",
      "En août 2025, son concert mémorable au festival de Oudhna aux côtés de son père a marqué une véritable réunion artistique entre tradition et renouveau. Mariem Noureddine apporte une dimension mystique, spirituelle et une énergie festive incomparable aux événements les plus prestigieux et authentiques.",
    ],
  },
  {
    id: 22,
    name: "Rayen Youssef",
    born: "Djerba, 1989",
    origin: "Djerba, Tunisie",
    specialty: "Pop Prodigy · Urban Arabe",
    styles: ["Pop Arabe", "Rap & Hip-Hop", "Modern Tounsi", "RnB"],
    experience: "+10 ans de carrière",
    location: "Djerba · Tunis · International",
    hit: "Ya Ghali",
    images: ["/chanteur/Rayen Youssef.jpeg"],
    bio: [
      "Rayen Youssef, né le 31 janvier 1989 à Djerba, est une figure incontournable de la pop urbaine tunisienne. Surnommé « l'Enfant Miracle » lors de sa révélation en 2014, il a su transformer ce mystère initial en une carrière solide et innovante, marquant la scène musicale par son style hybride et son charisme naturel.",
      "Naviguant avec aisance entre la pop mélodique et les influences rap/hip-hop, il collabore régulièrement avec des figures majeures de l'urbain comme Weld El 15 ou Si Lemhaf. Ses tubes tels que « Ya Ghali », « Dinero » et plus récemment « Mesalish » (2024) témoignent de sa capacité à capter l'air du temps et à séduire un public jeune et branché.",
      "Artiste aux multiples facettes, également remarqué pour ses talents d'acteur, Rayen Youssef apporte une touche résolument moderne et dynamique aux soirées d'exception. Sa maîtrise des sonorités contemporaines et son énergie communicative font de lui un artiste de choix pour des célébrations qui vibrent au rythme de la Tunisie d'aujourd'hui.",
    ],
  },
  {
    id: 23,
    name: "Sofien Zaidi",
    born: "Tunis, Tunisie",
    origin: "Tunis, Tunisie",
    specialty: "Malouf & Musique Mystique",
    styles: ["Malouf", "Soufi", "Classique Tunisien", "Musique de Chambre"],
    experience: "+20 ans de carrière",
    location: "Tunis · La Rachidia · International",
    hit: "Rjel Bledi",
    images: ["/chanteur/Sofien Zaidi.jpeg"],
    bio: [
      "Sofien Zaidi est un musicien et chanteur d'exception, figure de proue de la nouvelle génération dédiée au patrimoine musical tunisien. Diplômé avec excellence de l'Institut supérieur de musique de Tunis en 2007, il allie une rigueur académique rare à une passion profonde pour le Malouf et la musique mystique soufie.",
      "Multi-instrumentiste virtuose (luth, percussions), il est un pilier de l'illustre orchestre de la Rachidia dont il dirige le choral. Son parcours est jalonné de récompenses prestigieuses, dont le premier prix au Festival de la Musique Tunisienne, et de collaborations internationales qui l'ont mené de l'Institut du Monde Arabe à Paris jusqu'aux scènes de Londres et Memphis.",
      "Auteur-compositeur talentueux, il continue d'enrichir le patrimoine national avec des créations comme son dernier single « Ya marhba bi awlad saydi » (2025). Sofien Zaidi incarne l'élégance et la noblesse de l'art lyrique tunisien, offrant des prestations d'une grande finesse pour les événements les plus raffinés et culturels.",
    ],
  },
  {
    id: 24,
    name: "Aymen Lessigue",
    born: "Tunis, 1983",
    origin: "Tunis, Tunisie",
    specialty: "Pop Arabe & Variété",
    styles: ["Pop Arabe", "Modern Tounsi", "Electro-Pop", "Classique Arabe"],
    experience: "+15 ans de carrière",
    location: "Tunis · Le Caire · Carthage",
    hit: "fy Zlm llyl",
    images: ["/chanteur/Aymen Lessigue.jpeg"],
    bio: [
      "Aymen Lessigue, né le 26 juillet 1983 à Tunis, est une figure marquante de la pop tunisienne à l'échelle panarabe. Révélé en 2006 lors de la saison 3 de Super Star où il a terminé sur le podium, il s'est imposé grâce à une voix mélodieuse inspirée par la grande Warda, sa muse éternelle.",
      "Artiste moderne, il fusionne habilement les rythmes tunisiens avec des sonorités électro et techno, comme en témoigne son tube viral « fy Zlm llyl » avec ARTMASTA (plus de 22 millions de vues). Habitué de la scène prestigieuse de Carthage, il continue de séduire le public par son charisme et sa capacité à se renouveler sans cesse.",
      "Avec une carrière jalonnée de succès et une présence médiatique chaleureuse, Aymen Lessigue apporte une touche de glamour et de modernité à chaque événement. Sa maîtrise de la variété arabe contemporaine et son énergie communicative font de lui un artiste de choix pour des célébrations vibrantes et mémorables.",
    ],
  },
  {
    id: 25,
    name: "Olfa Ben Romdhane",
    born: "Tunisie, 1970",
    origin: "Tunis, Tunisie",
    specialty: "Tarab Romantique · Variété Arabe",
    styles: ["Romantique", "Tarab", "Folklorique", "Classique Arabe"],
    experience: "+30 ans de carrière",
    location: "Tunis · Hammamet · Carthage",
    hit: "Andi Ghzeli",
    images: ["/chanteur/Olfa Ben Romdhane.jpeg"],
    bio: [
      "Olfa Ben Romdhane, née en 1970, est l'une des voix féminines les plus envoûtantes de la chanson tunisienne. Forte d'une carrière lancée dans les années 90 et marquée par une collaboration prestigieuse avec la maison de disques Rotana, elle s'est imposée comme une référence du style romantique et du Tarab moyen-oriental.",
      "Sa capacité à fusionner les traditions folkloriques tunisiennes avec des sonorités arabes classiques lui a permis de conquérir les scènes les plus renommées, du Théâtre Romain de Carthage au Festival International de Hammamet où elle a triomphé en 2024. Ses succès comme « Andi Ghzeli » et « Mahla Zinou » sont des incontournables des soirées élégantes.",
      "Artiste d'une grande sensibilité, Olfa Ben Romdhane captive son public par une interprétation profonde et habitée. Sa maîtrise vocale et son élégance naturelle font d'elle une artiste d'exception, idéale pour sublimer les mariages et cérémonies où la noblesse de la musique arabe est à l'honneur.",
    ],
  },
  {
    id: 26,
    name: "Asma Othmani",
    born: "Tunis, 1987",
    origin: "Tunis, Tunisie",
    specialty: "Pop Arabe · Actrice · Animatrice",
    styles: ["Pop Arabe", "Traditionnel", "Chaoui", "Algérien"],
    experience: "+20 ans de carrière",
    location: "Tunis · International",
    hit: "Yama Lasmer Douni",
    images: ["/chanteur/Asma othmani.jpeg"],
    bio: [
      "Asma Othmani, née le 24 juin 1987 à Tunis, est une artiste aux multiples facettes : chanteuse, actrice et animatrice de talent. Révélée par ses passages remarqués dans Super Star et The Voice, elle s'est imposée comme une voix qui compte, capable de mêler la pop arabe aux influences bédouines, chaoui et algériennes.",
      "Au-delà de sa carrière à la radio (Mosaïque FM) et à la télévision (Awled Moufida), elle est reconnue pour son engagement sociétal. Sa reprise de « Yama Lasmer Douni » en 2017 est devenue l'hymne de la campagne contre le racisme #Tounes_Alwen, un hommage vibrant à sa mère et à la diversité de la Tunisie.",
      "Après une pause introspective de cinq ans, elle signe un retour magistral en 2026 avec « Nechki lel Bey », confirmant sa place d'artiste authentique et sereine. Asma Othmani apporte une dimension à la fois festive, moderne et profondément humaine aux événements les plus prestigieux.",
    ],
  },
  {
    id: 27,
    name: "Asma Ben Ahmed",
    born: "Tunisie, 1985",
    origin: "Tunisie",
    specialty: "Musique Orientale · Actrice",
    styles: ["Musique Moyen-Orientale", "Folklorique Arabe", "Classique Arabe", "Patrimoine Tunisien"],
    experience: "+20 ans de carrière",
    location: "Tunis · Monastir · International",
    hit: "Ghali wallah Ghali",
    images: ["/chanteur/Asma ben ahmed.jpeg"],
    bio: [
      "Asma Ben Ahmed, née le 21 juin 1985, est une artiste accomplie alliant une solide formation scientifique à une passion dévorante pour les arts. Diplômée en biologie et titulaire d'un master de l'Institut supérieur de musique de Tunis, elle s'est révélée au monde arabe en 2006 lors de la saison 3 de Super Star.",
      "Véritable virtuose de la musique moyen-orientale et folklorique, elle navigue avec élégance entre le patrimoine tunisien et le classique arabe, inspirée par la grandeur de Fairuz et Oum Kalthoum. De l'Opéra du Caire aux scènes prestigieuses de Carthage et Hammamet, elle captive par sa technique irréprochable et sa sensibilité.",
      "Également actrice remarquée dans la série « Qalb Edhiab », elle continue d'enrichir la scène culturelle, comme lors de sa performance éclatante à Monastir en mars 2026. Asma Ben Ahmed incarne l'excellence et le raffinement, offrant une dimension intemporelle et prestigieuse à chaque célébration d'exception.",
    ],
  },
  {
    id: 28,
    name: "Anis Letaïef",
    born: "Tunisie",
    origin: "Tunisie",
    specialty: "Pop Arabe · Variétés · Tarab",
    styles: ["Pop Arabe", "Tarab", "Classique Arabe", "Patrimoine Tunisien"],
    experience: "+20 ans de carrière",
    location: "Tunis · Carthage · International",
    hit: "Lella Ftima",
    images: ["/chanteur/Anis letaif.jpeg"],
    bio: [
      "Anis Letaïef est un artiste incontournable de la scène pop arabe et des variétés, reconnu pour sa voix puissante et son charisme naturel. Révélé par l'émission Superstar en 2005, il a su transformer ce tremplin en une carrière solide et diversifiée, marquée par une exigence artistique rare.",
      "Maître de la pop moderne sur une base musicale traditionnelle, il s'est imposé avec son hit « Lella Ftima » tout en rendant hommage aux géants de l'Orient (Abdel Halim, Warda). Sa spécialité réside également dans ses concerts narratifs uniques célébrant le patrimoine tunisien d'Ali Riahi et Hédi Jouini.",
      "De retour sur la prestigieuse scène de Carthage en 2025, il aborde 2026 avec une ambition renouvelée, préparant la sortie de quatre nouveaux titres en dialectes tunisien et égyptien. Anis Letaïef apporte une élégance moderne et une énergie vibrante aux événements les plus prestigieux du pays.",
    ],
  },
  {
    id: 29,
    name: "Mohamed Jbeli",
    born: "Tunisie, 1967",
    origin: "Tunis, Tunisie",
    specialty: "Variété Tunisienne & Arabe",
    styles: ["Tunisien", "Tarab", "Soufi", "Fusion"],
    experience: "+35 ans de carrière",
    location: "Tunis · Sousse · International",
    hit: "Nadhrat Ainek",
    images: ["/chanteur/Mohamed Jbeli.jpeg"],
    bio: [
      "Mohamed Jbeli, né le 27 octobre 1967, est l'une des voix les plus respectées de la chanson tunisienne. Révélé par l'émission Noujoum El Ghad, il a forgé son talent au sein de la Troupe Nationale Tunisienne, interprétant les chefs-d'œuvre du Tarab classique avant de s'imposer comme un compositeur prolifique avec plus de 50 créations mêlant influences soufies, turques et indiennes.",
      "En 2025, il a marqué l'actualité avec son titre « Ahayt Ahayt » et une tournée estivale triomphale à travers la Tunisie (Sousse, La Goulette, Salakta), tout en portant l'opérette nationale « Ana Chaâbk ». Son prestige dépasse les frontières, comme en témoigne son invitation en tant qu'invité d'honneur au Festival de la musique citadine d'Annaba en Algérie.",
      "Début 2026, il a confirmé son dynamisme avec le single « Ana Insen », réaffirmant sa place de pilier de la musique tunisienne moderne. Artiste complet, acteur et showman d'exception, Mohamed Jbeli apporte une maîtrise vocale absolue et une élégance intemporelle aux événements les plus prestigieux, célébrant l'unité et la passion du chant arabe.",
    ],
  },
  {
    id: 30,
    name: "Ahmed Rebai",
    born: "Tunis, 1997",
    origin: "Tunis, Tunisie",
    specialty: "Musique Arabe · Violoniste",
    styles: ["Musique Arabe", "Variété", "Classique Arabe", "Pop Arabe"],
    experience: "+15 ans de carrière",
    location: "Tunis · International",
    hit: "Nedem",
    images: ["/chanteur/Ahmed rbai.jpeg"],
    bio: [
      "Ahmed Rebai, né le 27 octobre 1997 à Tunis, est l'un des talents les plus prometteurs de la nouvelle scène arabe. Neveu du légendaire Saber Rebaï et fils du musicien professionnel Wajdi Rebaï, il porte avec brio un héritage familial prestigieux. Diplômé en musicologie de l'ISM de Tunis, il allie une formation académique rigoureuse à une maîtrise virtuose du violon.",
      "Signé sous le prestigieux label Rotana, il a su s'imposer dès ses débuts avec son album « Waad » en 2019. Ses succès comme « Nhebbek Men Ghir Tfalsif » et son titre primé « Nedem » — lauréat du premier prix au Festival de la chanson tunisienne en 2021 — témoignent de sa capacité à réinventer le classique avec une touche de modernité.",
      "En 2025, il prépare un album ambitieux explorant divers dialectes arabes (libanais, égyptien, algérien), affirmant son désir de porter la culture tunisienne au-delà des frontières. Ahmed Rebai apporte une élégance rare et une puissance vocale exceptionnelle aux événements les plus prestigieux, incarnant avec passion la relève de la noblesse musicale tunisienne.",
    ],
  },
  {
    id: 31,
    name: "Rami Khalil",
    born: "Tunisie",
    origin: "Tunisie",
    specialty: "Variété Populaire",
    styles: ["Variété", "Show"],
    experience: "+10 ans de carrière",
    location: "Tunis",
    hit: "Spectacle Live",
    images: ["/chanteur/rami khalil.jpeg"],
    bio: [
      "Rami Khalil est un artiste talentueux de la scène tunisienne, reconnu pour ses performances énergiques et sa voix mélodieuse.",
      "Habitué des grandes scènes et des événements festifs, il apporte une ambiance unique à chaque célébration.",
      "Sa présence sur scène et son répertoire varié en font un artiste apprécié pour tous les types d'événements prestigieux.",
    ],
  },
  {
    id: 32,
    name: "Fahmi Riahi",
    born: "Tunisie",
    origin: "Tunis, Tunisie",
    specialty: "Avant-Garde Tunisienne",
    styles: ["Alternatif", "Pop Expérimentale", "Indie Arabe", "Folk Moderne"],
    experience: "+10 ans de carrière",
    location: "Tunis · Doha · Hammamet",
    hit: "Allah Ysemhek",
    images: ["/chanteur/Fahmi Riahi.jpeg"],
    bio: [
      "Fahmi Riahi est un artiste audacieux et visionnaire qui redéfinit les contours de la musique tunisienne d'avant-garde. Depuis le début des années 2010, il s'est imposé comme une figure incontournable de la scène alternative, proposant des expériences sonores nouvelles qui bousculent les codes établis tout en respectant l'âme de la mélodie tunisienne.",
      "Collaborateur régulier du groupe Bendirman et proche d'artistes engagés comme Yasser Jradi, il est réputé pour sa capacité à « donner l'image aux sons ». Sa participation à des projets d'envergure, comme le Bendirman Orchestra à Hammamet, témoigne de sa maîtrise scénique et de son talent de compositeur, illustré récemment par son titre « Allah Ysemhek » (2024).",
      "De Tunis à Doha, où il s'est produit avec succès au St. Regis, Fahmi Riahi captive par son authenticité et sa quête perpétuelle d'innovation. Sa présence apporte une dimension artistique profonde et résolument moderne aux événements d'exception, idéale pour un public en quête de découvertes musicales authentiques et sophistiquées.",
    ],
  },
  {
    id: 33,
    name: "Moez Troudi",
    born: "Tunisie",
    origin: "Tunisie",
    specialty: "Maître du Malouf · Directeur de la Rachidia",
    styles: ["Malouf", "Arabo-Andalou", "Classique Tunisien", "Patrimoine"],
    experience: "+25 ans de carrière",
    location: "Tunis · La Rachidia · International",
    hit: "Patrimoine National",
    images: ["/chanteur/Moez troudi.jpeg"],
    bio: [
      "Moez Troudi est un éminent chanteur et musicien tunisien, figure de proue de la préservation du patrimoine musical national. Directeur de l'illustre Association de la Rachidia, il consacre sa vie à la sauvegarde et à la promotion du Malouf, pilier de l'identité sonore de la Tunisie.",
      "Spécialiste incontesté de la musique arabo-andalouse classique, il se distingue par une rigueur académique alliée à une sensibilité profonde. Son art, loin des circuits commerciaux, puise sa force dans les racines séculaires de la culture maghrébine, offrant des interprétations magistrales des répertoires traditionnels les plus raffinés.",
      "Artiste de prestige régulièrement invité dans les festivals culturels et les cérémonies nationales, Moez Troudi incarne la noblesse de l'art lyrique tunisien. Sa présence apporte une dimension historique et une élégance intemporelle à chaque événement, célébrant la richesse et la pérennité d'un héritage musical d'exception.",
    ],
  },
  {
    id: 34,
    name: "Nadia Khaless",
    born: "Agadir, Maroc",
    origin: "Tunisie · Maroc",
    specialty: "Fusion Arabo-Andalouse",
    styles: ["Arabo-Andalou", "Patrimoine Maghrébin", "Pop Contemporaine", "Folk"],
    experience: "+10 ans de carrière",
    location: "Sfax · Tunis · Agadir",
    hit: "Hiloula",
    images: ["/chanteur/Nadia Khaless.jpeg"],
    bio: [
      "Nadia Khaless est une artiste d'exception qui incarne le pont culturel entre la Tunisie et le Maroc. Diplômée de l'Institut supérieur de musique de Sfax, elle possède un bagage académique solide qui lui permet de naviguer avec aisance entre la musique savante arabo-andalouse et les sonorités pop les plus modernes.",
      "Originaire d'Agadir mais ayant grandi en Tunisie, elle revisite avec brio les patrimoines musicaux du Maghreb, mêlant les influences berbères de sa ville natale aux traditions de Sfax et d'Alger. Son titre phare « Hiloula », avec plus de 3,5 millions de vues sur YouTube, témoigne de son succès populaire et de sa capacité à toucher un large public.",
      "Réputée pour sa voix puissante et sa grande sensibilité, Nadia Khaless apporte une dimension raffinée et authentique à chaque performance. Sa maîtrise des répertoires traditionnels alliée à une esthétique contemporaine en fait une artiste idéale pour les événements prestigieux qui célèbrent la richesse et la diversité de l'identité maghrébine.",
    ],
  },
  {
    id: 35,
    name: "Afrah",
    born: "Tunisie",
    origin: "Tunisie",
    specialty: "Révélation Pop & Patrimoine",
    styles: ["Pop Arabe", "Variété Tunisienne", "Patrimoine", "Modern"],
    experience: "Nouvelle Scène",
    location: "Tunis · Émissions TV",
    hit: "Farhna Ellila",
    images: ["/chanteur/Afrah singer.jpeg"],
    bio: [
      "Afrah est l'une des voix les plus prometteuses et étincelantes de la nouvelle génération musicale tunisienne. Titulaire d'un master en musique, elle allie une maîtrise technique irréprochable à une sensibilité artistique qui captive instantanément son auditoire.",
      "Depuis ses débuts remarqués lors de grands événements culturels et sur les plateaux télévisés, elle s'est imposée par un style moderne et envoûtant. Son premier single « Farhna Ellila », sorti en avril 2024, témoigne de son talent d'interprète capable de sublimer tant les créations originales que le patrimoine national.",
      "Réputée pour ses reprises habitées des classiques d'Oulaya ou d'Assala, Afrah apporte une touche personnelle et une émotion profonde à chaque performance. Avec trois nouvelles productions en préparation pour 2026, elle incarne le futur radieux de la chanson tunisienne, idéale pour des événements vibrants et élégants.",
    ],
  },
  {
    id: 36,
    name: "Khawla Tawes",
    born: "Tunisie",
    origin: "Tunis, Tunisie",
    specialty: "Révélation Pop Arabe",
    styles: ["Pop Arabe", "Modern Tounsi", "Variété"],
    experience: "Nouvelle Scène (2026)",
    location: "Tunis",
    hit: "Nestenna",
    images: ["/chanteur/Khawla Tawes.jpeg"],
    bio: [
      "Khawla Tawes est l'une des nouvelles voix les plus prometteuses de la scène musicale tunisienne émergente. Avec un timbre de voix frais et une détermination affirmée, elle fait une entrée remarquée dans l'univers de la pop arabe en 2026, captant immédiatement l'attention des mélomanes avertis.",
      "Son tout premier single « Nestenna », sorti en février 2026, est le fruit d'une collaboration avec le talentueux compositeur Aziz Hdaji. Ce titre, qui allie mélodie accrocheuse et interprétation sensible, marque le début d'un parcours qui s'annonce riche en succès et en découvertes artistiques.",
      "Représentant la nouvelle génération d'artistes qui montent, Khawla Tawes apporte une fraîcheur et une authenticité bienvenues. Sa présence est idéale pour des événements qui souhaitent mettre en avant les nouveaux talents de demain, offrant une expérience musicale inédite et pleine d'espoir pour l'avenir de la chanson tunisienne.",
    ],
  },
  {
    id: 37,
    name: "Maya Shane",
    born: "Meudon, France",
    origin: "Tunisie · France",
    specialty: "Diva Franco-Orientale",
    styles: ["Chanson Française", "Variété Orientale", "World Fusion", "Soul"],
    experience: "+20 ans de carrière",
    location: "Paris · Tunis · Miami · International",
    hit: "On vient tous d'un ailleurs",
    images: ["/chanteur/Maya Shane.jpeg"],
    bio: [
      "Maya Shane, surnommée la « Diva franco-orientale », est une auteure-compositrice-interprète d'exception née en France de parents tunisiens. Véritable trait d'union entre l'Orient et l'Occident, elle fusionne avec élégance la chanson française, le Tarab classique et même des rythmes congolais, créant un univers musical unique et sans frontières.",
      "Inspirée par des muses comme Dalida et ayant collaboré avec des géants tels qu'Enrico Macias, elle chante en cinq langues (français, arabe, anglais, hébreu, lingala). Ses albums, de « Les Filles d'Orient » à « Les Couleurs de l'espoir », portent des messages universels d'amour, de paix et de résilience, touchant les cœurs aux quatre coins du globe.",
      "De Paris à Miami, en passant par l'Asie et l'Europe, Maya Shane captive par son charisme et sa profondeur. Sa voix cosmopolite et son répertoire multiculturel apportent une dimension internationale et raffinée aux événements d'exception, célébrant l'unité à travers la diversité des sons et des cultures.",
    ],
  },
  {
    id: 38,
    name: "Marwa Chahine",
    born: "Tunisie",
    origin: "Tunisie",
    specialty: "Variété Tunisienne",
    styles: ["Variété", "Show"],
    experience: "+10 ans de carrière",
    location: "Tunis",
    hit: "Spectacle Live",
    images: ["/chanteur/Marwa chahine.jpeg"],
    bio: [
      "Marwa Chahine est une chanteuse talentueuse de la scène tunisienne, appréciée pour sa voix mélodieuse et son élégance sur scène.",
      "Elle se produit régulièrement dans les plus grands hôtels et lors d'événements prestigieux, offrant un répertoire varié et raffiné.",
      "Son professionnalisme et son sens de la fête font d'elle une artiste de choix pour sublimer vos cérémonies et soirées.",
    ],
  },
  {
    id: 39,
    name: "Zaza Show",
    born: "Tunis, Tunisie",
    origin: "Tunis, Tunisie",
    specialty: "Mezoued Moderne · Showwoman",
    styles: ["Mezoued", "Pop Arabe", "Traditionnel", "Engagé"],
    experience: "+15 ans de carrière",
    location: "Tunis · Hammamet · International",
    hit: "Dima 7ora",
    images: ["/chanteur/Zaza.jpeg"],
    bio: [
      "Zaza, de son vrai nom Zeineb Sawen, est l'une des artistes les plus populaires et influentes de la scène tunisienne actuelle. Véritable icône du Mezoued moderne, elle a commencé son ascension en 2010 et s'est imposée grâce à une énergie débordante et un style qui fusionne parfaitement pop arabe et traditions populaires.",
      "Au-delà du divertissement, Zaza est connue pour son engagement, notamment à travers son titre phare « Dima 7ora » (Toujours libre), un hommage vibrant aux femmes tunisiennes. Avec plus de 2,2 millions d'abonnés sur Instagram, elle est une voix qui compte et qui rassemble toutes les générations autour de la fête.",
      "Reine des mariages et des grands événements à Hammamet et partout en Tunisie, elle a sorti en 2025 le single « Alech Hia » pour réaffirmer sa place d'artiste vocale accomplie. Sa présence garantit un spectacle total, où la puissance de la tradition rencontre la modernité d'une femme libre et passionnée.",
    ],
  },
  {
    id: 40,
    name: "Nordo",
    born: "Tunis, 1990",
    origin: "Tunis, Tunisie",
    specialty: "Hip-Hop · Pop · Acteur",
    styles: ["Hip-Hop", "R&B", "Pop", "Afro-Trap", "Flamenco", "Gnawa"],
    experience: "+20 ans de carrière",
    location: "Tunis · International",
    hit: "3arbouch",
    images: ["/chanteur/Nordo.jpeg"],
    bio: [
      "Nordo, de son vrai nom Marwen Jbeli, né le 29 février 1990 à Tunis, est l'une des figures les plus influentes et charismatiques de la scène urbaine maghrébine. Parti de rien et ayant grandi dans la précarité, il a su transformer ses luttes en une force créative phénoménale, s'imposant comme un artiste complet : rappeur, chanteur, compositeur, acteur et danseur.",
      "Son ascension fulgurante en 2020 avec les tubes planétaires « 3arbouch » (187M de vues) et « Ya Denya » (105M de vues) a marqué un tournant. Sa voix feutrée (« smoky ») navigue avec aisance entre hip-hop, R&B et soul du raï, une polyvalence qui lui a permis de collaborer avec Balti, Ahmed Saad et de faire la couverture de Billboard Arabia en 2025 pour son album « Cotinga ».",
      "Consécration ultime, celui qui écoutait ses idoles derrière les murs du Festival de Carthage y est retourné en 2023 comme tête d'affiche à guichets fermés. Artiste authentique écrivant lui-même ses textes, Nordo apporte une énergie brute, une modernité percutante et un prestige international aux événements les plus glamours, incarnant l'oiseau rare de la musique tunisienne.",
    ],
  },
];
