/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingPlannerRouteImport } from './routes/wedding-planner'
import { Route as IndexRouteImport } from './routes/index'

const WeddingPlannerRoute = WeddingPlannerRouteImport.update({
  id: '/wedding-planner',
  path: '/wedding-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wedding-planner': typeof WeddingPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wedding-planner': typeof WeddingPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wedding-planner': typeof WeddingPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wedding-planner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wedding-planner'
  id: '__root__' | '/' | '/wedding-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WeddingPlannerRoute: typeof WeddingPlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding-planner': {
      id: '/wedding-planner'
      path: '/wedding-planner'
      fullPath: '/wedding-planner'
      preLoaderRoute: typeof WeddingPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WeddingPlannerRoute: WeddingPlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
